include:
  - ./nextcloud/docker-compose.yaml
  - ./copyparty/docker-compose.yaml
services:
  tunnel:
    image: cloudflare/cloudflared
    restart: always
    env_file:
      - .tunnel.env
    command: tunnel run
    environment:
      NO_AUTOUPDATE: true
    networks:
      - tunnel
  pastebin:
    extends:
      file: ./pastebin/docker-compose.yaml
      service: pastebin
    networks:
      - tunnel

networks:
  tunnel:
