#!/usr/bin/env bash
# setup.sh – bootstraps the local environment for the infra Terraform config
# Run from the repo root:  bash setup.sh
set -eo pipefail

# ─────────────────────────────────────────────────────────────────────────────
# CHECK if all ENV VARS required are set
# ─────────────────────────────────────────────────────────────────────────────
check_env_vars() {
  local count=0
  for i in $@; do
    if [ -z "${!i}" ]; then
      echo "Please set env var $i" >&2
      count=$((count + 1))
    fi
  done
  if [ $count -gt 1 ]; then
    exit 1
  fi
}

if [ ! -f data/env.sh ]; then
  echo '
  Setup script expects env vars to be set or calls
  data/env.sh to set them up
  If you dont have a way to put them into your env,
  please create env.sh inside data/ directory
  ' >&2
else
  . data/env.sh
fi

check_env_vars \
  SHARE_FOLDER \
  SYNC_FOLDER \
  SYNCTHING_CONFIG \
  N8N_DATA \
  NGINX_CERTS \
  PASTEBIN_SOURCE \
  COPYPARTY_CONF

# ─────────────────────────────────────────────────────────────────────────────

BOLD="\033[1m"
GREEN="\033[32m"
YELLOW="\033[33m"
RESET="\033[0m"

info() { echo -e "${GREEN}[setup]${RESET} $*"; }
warn() { echo -e "${YELLOW}[warn] ${RESET} $*"; }
step() { echo -e "\n${BOLD}── $* ──${RESET}"; }

# ── 0. Prerequisites check ────────────────────────────────────────────────────
step "Checking prerequisites"

for cmd in docker terraform curl; do
  if command -v "$cmd" &>/dev/null; then
    info "$cmd found: $(command -v "$cmd")"
  else
    warn "$cmd NOT found – please install it before running terraform apply"
  fi
done

TERRAFORM_VERSION=$(terraform version -json 2>/dev/null | python3 -c "import sys,json; print(json.load(sys.stdin)['terraform_version'])" 2>/dev/null || echo "unknown")
info "Terraform version: $TERRAFORM_VERSION"

# ── 1. Create host directories ────────────────────────────────────────────────
step "Creating host data directories"

DIRS=(
  "$SHARE_FOLDER"
  "$SYNC_FOLDER"
  "$SYNCTHING_CONFIG"
  "$N8N_DATA"
  "$NGINX_CERTS"
)

for dir in "${DIRS[@]}"; do
  if [[ ! -d "$dir" ]]; then
    sudo mkdir -p "$dir"
    info "Created $dir"
  else
    info "Already exists: $dir"
  fi
done

# Fix ownership so Docker volumes are writable by the current user
sudo chown -R "$(id -u):$(id -g)" "$SYNCTHING_CONFIG" "$N8N_DATA" 2>/dev/null || true

# ── 2. Copy Dockerfile into pastebin source dir ───────────────────────────────
step "Setting up Pastebin Dockerfile"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOCKERFILE_SRC="$SCRIPT_DIR/infra/modules/pastebin/Dockerfile"

if [[ -f "$PASTEBIN_SOURCE/Dockerfile" ]]; then
  warn "Dockerfile already exists at $PASTEBIN_SOURCE/Dockerfile – skipping copy"
  warn "If you want the new multi-stage Dockerfile, copy it manually from $DOCKERFILE_SRC"
else
  if [[ -f "$DOCKERFILE_SRC" ]]; then
    cp "$DOCKERFILE_SRC" "$PASTEBIN_SOURCE/Dockerfile"
    info "Copied Dockerfile to $PASTEBIN_SOURCE/Dockerfile"
  else
    warn "Could not find $DOCKERFILE_SRC – run this script from the repo root"
  fi
fi

# ── 3. Create .rendered dir for nginx config ──────────────────────────────────
step "Creating nginx rendered config directory"
mkdir -p "$SCRIPT_DIR/infra/modules/copyparty/.rendered"
info "Created infra/modules/copyparty/.rendered/"

# ── 4. Generate self-signed TLS cert for local dev ───────────────────────────
step "Generating self-signed TLS certificate (local dev only)"

if [[ -f "$NGINX_CERTS/fullchain.pem" ]]; then
  info "Certs already exist at $NGINX_CERTS – skipping"
else
  if command -v openssl &>/dev/null; then
    sudo openssl req -x509 -nodes -days 3650 \
      -newkey rsa:2048 \
      -keyout "$NGINX_CERTS/privkey.pem" \
      -out "$NGINX_CERTS/fullchain.pem" \
      -subj "/CN=localhost" \
      2>/dev/null
    sudo chmod 644 "$NGINX_CERTS/fullchain.pem" "$NGINX_CERTS/privkey.pem"
    info "Self-signed cert written to $NGINX_CERTS/"
    warn "For production, replace with your real certs or use Cloudflare Full (strict)"
  else
    warn "openssl not found – you'll need to add TLS certs to $NGINX_CERTS manually"
  fi
fi

# ── 5. Write terraform.tfvars ─────────────────────────────────────────────────
step "Writing infra/terraform.tfvars"

TFVARS="$SCRIPT_DIR/infra/terraform.tfvars"

if [[ -f "$TFVARS" && "${OVERWRITE_TFVARS:-no}" != "yes" ]]; then
  warn "terraform.tfvars already exists – skipping (set OVERWRITE_TFVARS=yes to overwrite)"
else
  cat >"$TFVARS" <<EOF
# Auto-generated by setup.sh – edit as needed

docker_host = "unix:///var/run/docker.sock"

pastebin_source               = "$PASTEBIN_SOURCE"
share_folder_path             = "$SHARE_FOLDER"
docker_container_share_folder = "/share"
copyparty_conf_path           = "$COPYPARTY_CONF"

# Set your real domain here
share_domain = "share.example.com"

sync_folder             = "$SYNC_FOLDER"
syncthing_config_folder = "$SYNCTHING_CONFIG"

n8n_data_path = "$N8N_DATA"

# tunnel_token is read from TF_VAR_tunnel_token env var for security
# export TF_VAR_tunnel_token="eyJ..."
EOF
  info "Written $TFVARS"
fi

# ── 6. Add nginx certs volume to reminder ────────────────────────────────────
step "Nginx cert mount reminder"
warn "The nginx container expects certs at /etc/nginx/certs/ inside the container."
warn "Mount $NGINX_CERTS into the copyparty nginx container."
warn "Add this volumes block to infra/modules/copyparty/main.tf docker_container.nginx if not already present:"
echo ""
echo '  volumes {'
echo "    host_path      = \"$NGINX_CERTS\""
echo '    container_path = "/etc/nginx/certs"'
echo '    read_only      = true'
echo '  }'
echo ""

# ── 7. Print next steps ───────────────────────────────────────────────────────
step "Next steps"
cat <<EOF
  1. Edit infra/terraform.tfvars with your real domain and paths.

  2. Export your Cloudflare Tunnel token (never put it in tfvars):
       export TF_VAR_tunnel_token="eyJ..."

  3. Export a strong n8n encryption key:
       export TF_VAR_n8n_encryption_key="\$(openssl rand -hex 32)"

  4. Initialise Terraform:
       cd infra && terraform init

  5. Preview the plan:
       terraform plan

  6. Apply:
       terraform apply

  Service URLs after apply:
    Pastebin   → http://localhost:6083
    Copyparty  → http://localhost:6080  (or https://<domain> via tunnel)
    Syncthing  → http://localhost:6084
    n8n        → http://localhost:6085
EOF

