services:
  vaultwarden:
    image: vaultwarden/server:latest
    restart: unless-stopped
    env_file:
      - ${ENV_VW:-.env}
    volumes:
      - vw_data:/data/
    ports:
      - ${PORT_VW:-80}:80
    networks:
      - tunnel

volumes:
  vw_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $VW_DATA
