services:
  share:
    image: copyparty/ac
    restart: always
    volumes:
      - $CP_SHARE:/w
      - $CONF_CP:/cfg
      - cp_cache:/cache
    ports:
      - ${PORT_CP:-3923}:3923

volumes:
  cp_cache:
