services:
  share:
    image: docker.io/copyparty/ac
    restart: always
    volumes:
      - /media:/w
      - cp_data:/cfg
      - cp_cache:/cache
    ports:
      - ${PORT_CP:-3923}:3923
    networks:
      - tunnel

volumes:
  cp_cache:
  cp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $CONF_CP
